name: geocat-viz
channels:
  - conda-forge
  - ncar
dependencies:
  - python=3
  - geocat-comp
  - geocat-datafiles
  - cartopy
  - make
  - matplotlib
  - netcdf4
  - scikit-learn
  - sphinx
  - wrf-python
  - pip
  - pip:
      - pre-commit
