{% set name = "geocat-viz" %}
{% set version = "2023.03.0.post0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # url: https://github.com/NCAR/{{ name }}/archive/v{{ version }}.tar.gz   # For building from a specific tag's tarball
  # sha256: 6624ffb855cbe717a8eb624c7fa313a47bf1b3827e22f28f4dec8b2e298d47cd
  git_tag: v{{ version }}   # For building from a specific tag
  # git_rev: april # For building from main branch for debugging purposes
  git_url: https://github.com/NCAR/{{ name }}.git

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python >=3.8, <3.11
    - pip
    - setuptools
  run:
    - python >=3.8, <3.11
    - cartopy
    - cmaps
    - numpy
    - scikit-learn
    - xarray <=2023.02.0
    - metpy

test:
  requires:
    - pip
    - cmaps
    - numpy
    - matplotlib
    - scikit-learn
  imports:
    - geocat
    - geocat.viz
    # - geocat.viz.plot_classes
    # - geocat.viz.util
  commands:
    - pip check
  source_files:
    - src

about:
  home: https://geocat.ucar.edu/
  summary: GeoCAT-viz is a collection of utility functions to make Python plotting with Matplotlib and Cartopy more like NCL (NCAR Command Language).
  dev_url: https://github.com/NCAR/{{ name }}
  doc_url: https://{{ name }}.readthedocs.io'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NCAR/geocat # GeoCAT https://github.com/orgs/NCAR/teams/geocat
    - anissa111 # A. Zacharias https://github.com/anissa111
    - erogluorhan # O. Eroglu https://github.com/erogluorhan
    - hCraker # H. Craker https://github.com/hCraker
    - pilotchute # A. Kootz https://github.com/pilotchute
