{% set version = "2020.7.30.1" %}

package:
  name: geocat-viz
  version: {{ version }}

source:
  url: https://github.com/NCAR/geocat-viz/archive/v{{ version }}.tar.gz

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - matplotlib
    - cmaps
    - cartopy
    - xarray
    - scikit-learn

test:
  imports:
    - geocat.viz
    - geocat.viz.util
  requires:
    - cmaps
    - numpy
    - matplotlib
    - scikit-learn

about:
  home: https://geocat.ucar.edu/
  license: Apache 2.0
  license_file: LICENSE
  summary: 'GeoCAT-viz is a collection of utility functions to make Python plotting with Matplotlib and Cartopy more like NCL (NCAR Command Language).'

extra:
  recipe-maintainers:
    - erogluorhan
    - michaelavs
