name: geocat_viz_build
channels:
  - conda-forge
  - ncar
dependencies:
  - python>=3.8, <3.11
  - cartopy
  - make
  - matplotlib
  - sphinx
  - pip
  - cmaps
  - numpy
  - xarray
  - metpy
  - pip:
      - pre-commit
      - scikit-learn
