name: geocat_viz_build
channels:
  - conda-forge
dependencies:
  - python>=3.8, <=3.10
  - cartopy
  - make
  - matplotlib<=3.5
  - sphinx
  - pip
  - cmaps
  - numpy
  - xarray
  - metpy
  - pint<=0.19
  - pip:
      - pre-commit
      - scikit-learn
